### ISSUE TITLE
How to use this as I see the extension but no operational way

### ISSUE THREAD

**Issue by vickydhas** [simonwhitaker/app-id-sanity#8]
Hello Developer,

 I installed this extension but cannot find checkbox or way to use this.

I have like 400+ App Id created due to XCode automatic provisioning and i want to get rid of those unwanted using checkbox rather one by one. 

How to use this please help.

Thanks.

**Comment by simonwhitaker** [comment]
I haven't touched this project in over 5 years. I doubt very much it still works.
